### ISSUE TITLE
[BUG] Core Hounds Call set bonus summon aggros everything nearby

### ISSUE THREAD

**Issue by Frankensteak** [ClassicWoWCommunity/tbc-classic-bugs#11]
#### 1.1. Core Hounds Call  2pc Corehound Summon does an AoE taunt for a ridiculously large range (suspected 100 yards)
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Equip Core Hounds Call Set with un-aggroed mobs nearby, but outside of aggro range
           2. Trigger the Corehound Summon
           3. See the mobs aggro

**Comment by Artemishowl** [comment]
This should already be fixed, we have another hotfix in flight too for the Corehound one in particular!
