### ISSUE TITLE
[BUG][ITEM SET] Warlord's Wartide showing an extra 6pc bonus?

### ISSUE THREAD

**Issue by kayla-glick** [ClassicWoWCommunity/tbc-classic-bugs#18]
#### 1.1. Description
The Shaman PVP set [Warlord's Wartide](https://www.wowhead.com/classic/item-set=1733/warlords-wartide) is currently showing two different 6pc bonuses on Wowhead. This may just be a Wowhead data-mining issue but I wanted to report it just in case.

#### 1.2. How to Reproduce
1. Obtain Warlord's Wartide gear
2. Check the set bonuses
#### 2.1. Description
I'm unsure if this is intended or even an issue at all and just a Wowhead issue.
#### 2.2 Source Material
![Image](https://github.com/user-attachments/assets/86812ecf-bda6-4a57-bbe8-f87a84089add)

**Comment by raethkcj** [comment]
Appears to be fixed; the second one is correct and the first one  was the error.
